# Oak-D Lite

- P: projection matrix, transforms world to camera frame
- K: camera intrinsics matrix
- [R|t]: extrinsics matrix

$$
\begin{align}
\begin{bmatrix} u \\ v \\ 1 \end{bmatrix} &= P \begin{bmatrix} X_w \\ Y_w \\ Z_w \\ 1 \end{bmatrix}\\
P &= KI[R|t] \\
\text{Extrinsics ([R|t])} &= \left [ \begin{matrix} r_{00} & r_{01} & r_{02} & T_x \\ r_{10} & r_{11} & r_{12} & T_y \\ r_{20} & r_{21} & r_{22} & T_z \\ 0 & 0 & 0 & 1 \end{matrix} \right ] \\
I &= \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
\end{bmatrix} \\
\text{Intrinsic Matrix (K)} &= \left [ \begin{matrix} f_x & 0 & c_x \\ 0 & f_y & c_y \\ 0 & 0 & 1 \end{matrix} \right ] \\
\end{align}
$$

## Calibration Data

```python
device = dai.Device()
calibData = device.readCalibration()
json = calibData.eepromToJson()
```

Other functions for `calibData`:

 - `calibData.eepromToJson()`
 - `calibData.eepromToJsonFile()`
 - `calibData.fromJson()`
 - `calibData.getBaselineDistance(1,2)`: distance from camera 1 (origin) to camera 2
 - `calibData.getCameraExtrinsics(1,2)`: matrix (4x4) from camera 1 (origin) to camera 2
 - `calibData.getCameraIntrinsics()`: camera K matrix
 - `calibData.getCameraToImuExtrinsics()`
 - `calibData.getCameraTranslationVector()`
 - `calibData.getDefaultIntrinsics()`
 - `calibData.getDistortionCoefficients()`
 - `calibData.getDistortionModel()`
 - `calibData.getEepromData()`
 - `calibData.getFov(1)`: field of view for camera 1
 - `calibData.getImuToCameraExtrinsics()`
 - `calibData.getLensPosition()`
 - `calibData.getStereoLeftCameraId()`: get camera identifier (e.g., `dai.CameraBoardSocket.CAM_A`) for left stereo caemra
 - `calibData.getStereoLeftRectificationRotation()`: get camera rotation matrix (3x3)
 - `calibData.getStereoRightCameraId()`: get camera identifier for right stereo camera
 - `calibData.getStereoRightRectificationRotation()`: get camera rotation matrix (3x3)

## Distortion

`calibData.getDistortionCoefficients()` returns: [`k1`,`k2`,`p1`,`p2`,`k3`,`k4`,`k5`,`k6`,`s1`,`s2`,`s3`,`s4`,`τx`,`τy`]




In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import depthai as dai
import numpy as np
# from pprint import pprint
# from collections import namedtuple
np.set_printoptions(suppress=True)
np.set_printoptions(precision=3)
from oaklib import *
# import yaml
# from dataclasses import dataclass
# from colorama import Fore

In [3]:
# params = save_camera_params("oak.yml")

In [4]:
imgs, imu, caminfo = load_oak("move")
print(caminfo)

Oak Camera Save -------------------
 Location: move
 Images: 1000
 IMU: 6000
Left Camera[480,640]----------------------
  focalLength(x,y): 452.3 452.5 px 
  principlePoint(x,y): 330.4 255.6 px
  distortionCoeffs: [-0.293 -5.79  -0.     0.001  6.169 -0.353 -5.614  6.038  0.     0.
  0.     0.     0.     0.   ]
  FOVH: 72.9000015258789
  Rotation: 
    [[ 1.     0.009 -0.017]
     [-0.009  1.     0.008]
     [ 0.017 -0.008  1.   ]]
  Translation: 
    [[-7.528]
     [ 0.026]
     [-0.051]]
  Distortion
    Radial: -0.293 -5.790 6.169 -0.353 -5.614 6.038
    Tangental: -0.000 0.001
    Other: 0.000 0.000 0.000 0.000 0.000 0.000
Right Camera[480,640]----------------------
  focalLength(x,y): 454.6 454.2 px 
  principlePoint(x,y): 314.0 256.0 px
  distortionCoeffs: [-1.709 -0.871  0.    -0.001  2.057 -1.731 -0.814  2.02   0.     0.
  0.     0.     0.     0.   ]
  FOVH: 72.9000015258789
  Rotation: 
    [[ 1.    -0.004  0.006]
     [ 0.004  1.    -0.005]
     [-0.006  0.005  1.   ]]
  Trans

In [5]:
c = OakCameraInfo("oak.yml")
print(c)

Left Camera[480,640]----------------------
  focalLength(x,y): 452.3 452.5 px 
  principlePoint(x,y): 330.4 255.6 px
  distortionCoeffs: [-0.293 -5.79  -0.     0.001  6.169 -0.353 -5.614  6.038  0.     0.
  0.     0.     0.     0.   ]
  FOVH: 72.9000015258789
  Rotation: 
    [[ 1.     0.009 -0.017]
     [-0.009  1.     0.008]
     [ 0.017 -0.008  1.   ]]
  Translation: 
    [[-7.528]
     [ 0.026]
     [-0.051]]
  Distortion
    Radial: -0.293 -5.790 6.169 -0.353 -5.614 6.038
    Tangental: -0.000 0.001
    Other: 0.000 0.000 0.000 0.000 0.000 0.000
Right Camera[480,640]----------------------
  focalLength(x,y): 454.6 454.2 px 
  principlePoint(x,y): 314.0 256.0 px
  distortionCoeffs: [-1.709 -0.871  0.    -0.001  2.057 -1.731 -0.814  2.02   0.     0.
  0.     0.     0.     0.   ]
  FOVH: 72.9000015258789
  Rotation: 
    [[ 1.    -0.004  0.006]
     [ 0.004  1.    -0.005]
     [-0.006  0.005  1.   ]]
  Translation: 
    [[ 3.77 ]
     [-0.02 ]
     [-0.169]]
  Distortion
    Radial: 

In [9]:
# np.hstack((c.left.R,c.left.t))

In [12]:
# k = camera.calibData.getCameraExtrinsics(dai.CameraBoardSocket.CAM_B,dai.CameraBoardSocket.CAM_C)
# np.array(k)
# camera.calibData.getCameraIntrinsics(dai.CameraBoardSocket.CAM_B)

In [13]:
# camera.calibData.getCameraToImuExtrinsics(dai.CameraBoardSocket.CAM_A)

In [14]:
# camera.calibData.getStereoLeftCameraId()

In [15]:
# camera.calibData.getFov(camera.calibData.getStereoLeftCameraId())

In [16]:
# camera.calibData.getStereoLeftRectificationRotation()

In [17]:
# camera.calibData.getLensPosition(dai.CameraBoardSocket.CAM_A)

In [18]:
# camera.json

In [19]:
# camera.calibData.getDistortionCoefficients(dai.CameraBoardSocket.CAM_A)